### ISSUE TITLE
What is the use of `AnyValidatable` struct?

### ISSUE THREAD

**Issue by karolkulesza** [SvenTiigi/ValidatedPropertyKit#1]
Cool repo ;-) 
I haven't seen the usage of `AnyValidatable` struct anywhere, though.

**Comment by SvenTiigi** [comment]
Hey @karolkulesza,

`AnyValidatable` is just a simple `Type-Erasure` for the `Valiatable` protocol. 

It is embedded in ValidatedPropertyKit in case you want to pass around a `Validatable` type as it has associated type requirements.

But it is correct that it is currently not used inside the Kit 👌

**Comment by SvenTiigi** [comment]
Closing due inactivity. Feel free to re-open the issue at any time.
