### ISSUE TITLE
Referencing initializer 'init(wrappedValue:_:nilValidation:)' on 'Validated' requires that 'Published<String>' conform to 'Optionalable'

### ISSUE THREAD

**Issue by JulesMoorhouse** [SvenTiigi/ValidatedPropertyKit#10]
## ValidatedPropertyKit Environment

- ValidatedPropertyKit version:
0.0.5

- macOS version:
11.6.2

- Xcode version:
13.2.1

- Dependency manager (Carthage, CocoaPods, SPM, Manually):
SPM

## What did you do?

I'm using a view model.
```
import CoreData
import Foundation
import ValidatedPropertyKit

extension EditView {
    class ViewModel: NSObject, ObservableObject {
        let item: Item
        let add: Bool
        let hasRelationship: Bool

        private let dataController: DataController

        @Validated(!.isEmpty)
        @Published var title = "" <= error
        // @Published var title: String <= error 
```

## What did you expect to happen?
To access the variable as shown in the readme examples.

## What happened instead?

Error....
```
Referencing initializer 'init(wrappedValue:_:nilValidation:)' on 'Validated' requires 
that 'Published<String>' conform to 'Optionalable'
```

I'm not sure why this is occurring?

Thanks in advance.

**Comment by SvenTiigi** [comment]
Hi @JulesMoorhouse,

As you are applying the `@Validated` property wrapper to an `@Published` declared property the resulting type of the Validated property wrapper is a `Published<String>` which results in a compile error as the `isEmpty` validation rule can only be applied to types that conform to the `Collection` protocol.

https://github.com/SvenTiigi/ValidatedPropertyKit/blob/1fc8adb98ce016700645ef17161c4583a8200cee/Sources/Validation/Validation%2BCollection.swift#L16

PS: The error message that Xcode shows is a little bit confusing the correct error message should be:
```
Static property 'isEmpty' requires that 'Published<String>' conform to 'Collection'
```

**Comment by JulesMoorhouse** [comment]
Thanks for your reply @SvenTiigi what do you suggest I do to fix the problem.

**Comment by SvenTiigi** [comment]
As the `Published` type does not expose a wrapped value there is sadly no way to access the underlying value to validate.
