### ISSUE TITLE
Support for iOS 13.x?

### ISSUE THREAD

**Issue by mylogon341** [SvenTiigi/ValidatedPropertyKit#12]
# Motivation
> ℹ My app needs to support iOS 13 and this package requires 14

# Solution
> ℹ There only seems to be one incompatible thing, which is the use of `@StateObject` in `Validated`

# Additional context 
> ℹ This doesn't look like it's too difficult of a change. Would it be a case of changing the `@StateObject` to maybe an `@ObservedObject` and calling it a day?

**Comment by SvenTiigi** [comment]
Fixed with version [`0.0.6`](https://github.com/SvenTiigi/ValidatedPropertyKit/releases/tag/0.0.6)
