### ISSUE TITLE
Validation on UITextField and UITextView

### ISSUE THREAD

**Issue by titiphoque** [SvenTiigi/ValidatedPropertyKit#4]
# Motivation
It could be really cool if we could use @Validated on UITextField and UITextView to simplify form validation. 

# Solution
I don't have any solution yet but the purpose is to have :
`@Validated(.nonEmpty) var myTextField: UITextField`
`@Validated(.hasPrefix("prefix") var myTextView: UITextView`

And to have a new class Validator which can validate a list of specific @Validated.
`let validator = Validator()`
`validator.add(myTextField)`
`validator.add(myTextView)`
`let isFormValid = validator.isValid()`

# Additional context 
I use UITextField as example but it could be applied to any UIKit components, example:
`@Validated(.isOn or .ifOff) var mySwitch: UISwitch`
`@Validated(.range(13...)) var myStepper: UIStepper`
 
I'm not sur if it's possible to easily adapt your code to UIKit components.

**Comment by SvenTiigi** [comment]
Hey @titiphoque,

Thanks for your detailed feature request.

Currently ValidatedPropertyKit can't be easily applied to UI related objects such as a `UISwitch` or `UIStepper` as the value of the property will be set to `nil` if the validation fails and of course this makes no sense for a UI related object such as a `UISwitch`.

But please feel free to open up a `PR` to get things started 👍
