### ISSUE TITLE
SwiftUI Integration

### ISSUE THREAD

**Issue by azamsharp** [SvenTiigi/ValidatedPropertyKit#5]
Do you have any example of using Validated package with SwiftUI, specially in the case of TextField.

**Comment by SvenTiigi** [comment]
Hey @azamsharp,

Currently ValidatedPropertyKit is focused on applying the `@Validated` PropertyWrapper to non UI related properties such as a `String`, `Int`, `Collection`, etc...

But feel free to open up a `PR` to get things started 👍

**Comment by duytph** [comment]
![Alt Text](https://media.giphy.com/media/J59c9F3Zhj0FvfVuxK/giphy.gif)

@azamsharp Hope you found a solution and share it with us.

It's late but I have a solution to make @Validated works with SwiftUI. The mandatory ideal is wrapping @Validated property in a struct for taking advantage of @Published, @State, ...
