### ISSUE TITLE
Please update the docs to add a real world example

### ISSUE THREAD

**Issue by azamsharp** [SvenTiigi/ValidatedPropertyKit#6]
Please update the docs to add a real world example. Even after reading the docs for 10 times it is hard to understand what and how to use this library.

**Comment by SvenTiigi** [comment]
Hey @azamsharp,

Sorry for the delayed response.

This is completely true. So far I haven't found the time to improve ValidatedPropertyKit
As ValidatedPropertyKit hasn't got an official 1.0 release there is a lot that should be improved.

Please feel free to open up a PR 👍

**Comment by rizwan95** [comment]
This is a much needed request! @SvenTiigi
