### ISSUE TITLE
Support validation for non NIL fields

### ISSUE THREAD

**Issue by andreimateiro** [SvenTiigi/ValidatedPropertyKit#8]
# Motivation
> There are many occasions where you have non nil Published variables in SwiftUI's ViewModel, validation of this kind of fields would be a nice addition.

**Comment by SvenTiigi** [comment]
Hey @andreimateiro,

Currently `ValidatedPropertyKit` requires an optional type in order to set `nil` on a `@Validated` property.

As soon as `ValidatedPropertyKit` hits a `1.0` release the support for non nil field will be available.
Please feel free to open up a PR.

**Comment by SvenTiigi** [comment]
Hey @andreimateiro,

Please check out the latest release [`0.0.5`](https://github.com/SvenTiigi/ValidatedPropertyKit/releases/tag/0.0.5) of `ValidatedPropertyKit` which added support for non optional properties.
